<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(_CommonTargets)</TargetFrameworks>

		<AssemblyName>NivaesNivaes.DataModel.Packer</AssemblyName>
		<RootNamespace>Nivaes.DataModel.Packer</RootNamespace>
		
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<IsAotCompatible>true</IsAotCompatible>
		<OptimizationPreference>Speed</OptimizationPreference>
	</PropertyGroup>

</Project>
