<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(_CommonTargets)</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<IsAotCompatible>true</IsAotCompatible>
		<OptimizationPreference>Speed</OptimizationPreference>
	</PropertyGroup>

</Project>
