<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFrameworks>netstandard2.1</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>

		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
	</PropertyGroup>



</Project>
